"""create new colume code in room

Revision ID: 0990ffdeeada
Revises: 342ca46130f9
Create Date: 2026-03-07 04:53:29.807146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0990ffdeeada'
down_revision: Union[str, Sequence[str], None] = '342ca46130f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_rooms_code'), 'rooms', ['code'], unique=True , )
    # ### end Alembic commands ###
    op.execute(
        "UPDATE rooms SET code = substring(md5(random()::text),1,6)"
    )
    op.alter_column(
        "rooms",
        "code",
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_code'), table_name='rooms')
    op.drop_column('rooms', 'code')
    # ### end Alembic commands ###
