"""update colum name revoked to revoke

Revision ID: 342ca46130f9
Revises: 01709930dade
Create Date: 2026-02-28 09:41:20.470892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342ca46130f9'
down_revision: Union[str, Sequence[str], None] = '01709930dade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoke', sa.Boolean(), nullable=False))
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'revoke')
    # ### end Alembic commands ###
